service: demo-service

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
      Resource: 'arn:aws:dynamodb:eu-west-2:906378793207:table/notes'

functions:
  healthCheck:
    handler: handler.health
    events:
      - http:
          path: /health
          method: get
  createNote:
    handler: note.create
    events:
      - http:
          path: /notes
          method: post
  getNote:
    handler: notes.get
    events:
      - http:
          path: /notes/{id}
          method: get

resources:
  Resources:
    NotesTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: notes
        AttributeDefinitions:
          - 
            AttributeName: id
            AttributeType: S
        KeySchema:
          - 
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1